// <auto-generated />
namespace StudentEvaluatorConsoleApp.Migrations
{
	using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CategoryNameIsUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CategoryNameIsUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201310070652287_CategoryNameIsUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
